### PR TITLE
Bugfix for unpublished page + Too many forward attempts

### PR DESCRIPTION
**Pull request by Jako**
http://forums.modx.com/thread/45611/try-to-load-unpublished-page-too-many-forward-attempts

### CODE REVIEW

**Comment by fourroses666** [comment]
This is added here: https://github.com/fourroses666/YAMS

**Comment by goldsky** [comment]
pls update the branch, and submit new pull request

**Comment by Jako** [comment]
@Deesen has already adopted my commit and added it to PR #10. https://github.com/Deesen/YAMS/commit/31bb3f3b2f280483272bb3950889a4630972ab34

**Comment by Jako** [comment]
I am done with YAMS. It has too many parsing and caching issues.

**Comment by Deesen** [comment]
Firstly BIG THANKS for providing tools like MultiTV etc., without them I would not be "modxed" like I am! I want to ask, does these YAMS-issues really beat the advantages? Which alternative do you use?

**Comment by Jako** [comment]
Thanks. I use Revo/Babel now.

**Comment by fourroses666** [comment]
There is EvoBabel for Evolution (Russian), https://github.com/webber12/evobabel-0.2

Never tried it. I think its not how YAMS does it, just seperate folders in back-end/manager.
I really like the YAMS tabs way. The disadvantage is a resource is in all languages even if you just want one.

**Comment by Deesen** [comment]
I work a lot with Revo too and know its caching and nesting issues and the core is such a monster in comparison to Evo with all its ExtJS. Built a site with Babel / MIGX-Blocklayout etc recently and as soon as I turn on the cache, the layout brakes into pieces! Also nested placeholder-modifiers are sooo time-consuming sometimes.. So I need the same workaround-philosophy in Revo like I got used to in Evo.

Just BTW: In 1.1 the evalSnippets() has changed and allows a lot more nested snippet-calls. Would be great to know if that solves some of these issues: https://github.com/modxcms/evolution/pull/467#issuecomment-172876335

**Comment by Jako** [comment]
The YAMS approach is somehow wrong: Having all languages parsed, rendered and cached together and throw away all but the current language when the page is shown. A client had a lot of issues with blank pages in one or two languages with that (caused by PHx if/else clauses and the YAMS parsing/rendering/caching approach).

I never develop sites in Revo switching off the cache. Cache as much as you can is my Revo approach from start. Mark Hamstra wrote a good article on that: https://www.markhamstra.com/modx/2011/10/caching-guidelines-for-modx-revolution/

**Pull request closed without merging**
